version: "3.7"

services:
  sonarqube:
    container_name: sonarqube
    stop_grace_period: 90s
    restart: unless-stopped
    command: -Dsonar.ce.javaOpts=-Xmx3072m -Dsonar.web.javaOpts=-Xmx3072m
    depends_on:
      - db
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - TZ=Europe/Budapest
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    container_name: sonar-postgres
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data


networks:
  sonarnet:
    name: sonarnet
    driver: bridge


volumes:
  sonarqube_conf:
    labels:
      project: sonarqube-compose
    driver: local
    driver_opts:
      type: none
      device: $PWD/sonarqube_conf
      o: bind
  sonarqube_data:
    labels:
      project: sonarqube-compose
    driver: local
    driver_opts:
      type: none
      device: $PWD/sonarqube_data
      o: bind
  sonarqube_extensions:
    labels:
      project: sonarqube-compose
    driver: local
    driver_opts:
      type: none
      device: $PWD/sonarqube_extensions
      o: bind
  sonarqube_db:
    labels:
      project: sonarqube-compose
    driver: local
    driver_opts:
      type: none
      device: $PWD/postgresql/data
      o: bind
